# Generated by Django 4.2.1 on 2023-06-07 16:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, validators=[accounts.validators.is_valid_national_code], verbose_name='کد ملی'),
        ),
    ]
