# Generated by Django 4.2.1 on 2023-06-07 20:13

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(unique=True, validators=[accounts.validators.is_valid_national_code], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(unique=True, validators=[accounts.validators.is_valid_phone_number], verbose_name='شماره موبایل'),
        ),
    ]
