# Generated by Django 4.2.1 on 2023-06-02 09:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('time', models.TimeField(choices=[(datetime.time(1, 30), '01:30'), (datetime.time(7, 30), '07:30'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 30), '10:30'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 30), '13:30'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 30), '16:30'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 30), '19:30'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 59), '23:59')], db_index=True, verbose_name='زمان')),
                ('status', models.CharField(choices=[('AVA', 'قابل رزرو'), ('UNA', 'غیر قابل رزرو'), ('BOK', 'رزرو شده')], db_index=True, default='AVA', max_length=10, verbose_name='وضعیت')),
                ('price', models.DecimalField(blank=True, decimal_places=3, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'روز رزرو',
                'verbose_name_plural': 'روز های رزرو',
                'db_table': 'reserve_system_table',
                'ordering': ['date'],
            },
        ),
    ]
