# Generated by Django 4.2.1 on 2023-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedatetime',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, null=True, verbose_name='هزینه'),
        ),
    ]
