# Generated by Django 4.2.1 on 2023-06-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_time', '0005_alter_reservedatetime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedatetime',
            options={'ordering': ['date'], 'verbose_name': 'روز رزرو', 'verbose_name_plural': 'روز های رزرو'},
        ),
    ]
