# Generated by Django 4.2.1 on 2023-06-04 08:45

from django.db import migrations, models
import utils.get_current_time


class Migration(migrations.Migration):

    dependencies = [
        ('table_time', '0006_alter_reservedatetime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedatetime',
            name='date',
            field=models.DateField(db_index=True, default=utils.get_current_time.get_current_time, verbose_name='تاریخ'),
        ),
    ]
