# Generated by Django 4.2.1 on 2023-06-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_time', '0007_alter_reservedatetime_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservedatetime',
            table='reserve_system_table_time',
        ),
    ]
