# Generated by Django 4.2.1 on 2023-06-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(verbose_name='نهایی شده/نشده')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('reserve_count', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد رزرو')),
                ('reserve_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_date_orders', to='table.reservedatetime', verbose_name='تاریخ رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'reserve_system_orders',
                'ordering': ['is_paid', '-reserve_date'],
            },
        ),
    ]
