# Generated by Django 4.2.1 on 2023-06-09 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('authority', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/نشده')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('reserve_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد جلسات رزرو')),
                ('final_price', models.DecimalField(decimal_places=0, default=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='قیمت')),
                ('reserve_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_date_orders', to='table.reservedatetime', verbose_name='تاریخ رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'reserve_system_orders',
                'ordering': ['is_paid', '-reserve_date'],
            },
        ),
    ]
