# Generated by Django 4.2.1 on 2023-06-09 14:49

import datetime
from django.db import migrations, models
import utils.get_current_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='قیمت سانس')),
                ('weekdays', models.CharField(choices=[('All', 'همه روز ها'), ('7', 'شنبه ها'), ('1', 'یکشنبه ها'), ('2', 'دوشنبه ها'), ('3', 'سه شنبه ها'), ('4', 'چهارشنبه ها'), ('5', 'پنجشنبه ها'), ('6', 'جمعه ها')], default='All', verbose_name='انتخاب روز های هفته')),
                ('times', models.CharField(choices=[('All', 'همه زمان ها'), ('01:30', '01:30'), ('07:30', '07:30'), ('09:00', '09:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('13:30', '13:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:00', '18:00'), ('19:30', '19:30'), ('21:00', '21:00'), ('22:30', '22:30'), ('23:59', '23:59')], default='All', verbose_name='انتخاب زمان های رزرو')),
            ],
            options={
                'verbose_name': 'تنظیم قیمت رزرو',
                'verbose_name_plural': 'تنظیمات قیمت رزرو',
                'db_table': 'reserve_system_price_setting',
            },
        ),
        migrations.CreateModel(
            name='ReserveDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=utils.get_current_time.get_current_time, verbose_name='تاریخ')),
                ('time', models.TimeField(choices=[(datetime.time(1, 30), '01:30'), (datetime.time(7, 30), '07:30'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 30), '10:30'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 30), '13:30'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 30), '16:30'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 30), '19:30'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 59), '23:59')], db_index=True, verbose_name='زمان')),
                ('status', models.CharField(choices=[('AVA', 'قابل رزرو'), ('UNA', 'غیر قابل رزرو'), ('BOK', 'رزرو شده')], db_index=True, default='AVA', max_length=10, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'روز رزرو',
                'verbose_name_plural': 'روز های رزرو',
                'db_table': 'reserve_system_table',
                'ordering': ['date'],
            },
        ),
    ]
