# Generated by Django 4.2.1 on 2023-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_reservedatetime_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='قیمت سانس')),
                ('weekdays', models.CharField(choices=[('All', 'همه روز ها'), ('Sat', 'شنبه ها'), ('Sun', 'یکشنبه ها'), ('Mon', 'دوشنبه ها'), ('Tue', 'سه شنبه ها'), ('Wed', 'چهارشنبه ها'), ('Thu', 'پنجشنبه ها'), ('Fri', 'جمعه ها')], default='All', verbose_name='انتخاب روز های هفته')),
                ('times', models.CharField(choices=[('All', 'همه روز ها'), ('01:30', 'T1'), ('07:30', 'T2'), ('09:00', 'T3'), ('10:30', 'T4'), ('12:00', 'T5'), ('13:30', 'T6'), ('15:00', 'T7'), ('16:30', 'T8'), ('18:00', 'T9'), ('19:30', 'T10'), ('21:00', 'T11'), ('22:30', 'T12'), ('23:59', 'T13')], default='All', verbose_name='انتخاب زمان های رزرو')),
            ],
        ),
        migrations.AddField(
            model_name='reservedatetime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservedatetime',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, null=True, verbose_name='قیمت'),
        ),
    ]
