# Generated by Django 4.2.1 on 2023-06-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_pricesetting_reservedatetime_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesetting',
            options={'verbose_name': 'تنظیم قیمت رزرو', 'verbose_name_plural': 'تنظیمات قیمت رزرو'},
        ),
    ]
