# Generated by Django 4.2.1 on 2023-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_pricesetting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='weekdays',
            field=models.CharField(choices=[('All', 'همه روز ها'), ('7', 'شنبه ها'), ('1', 'یکشنبه ها'), ('2', 'دوشنبه ها'), ('3', 'سه شنبه ها'), ('4', 'چهارشنبه ها'), ('5', 'پنجشنبه ها'), ('6', 'جمعه ها')], default='All', verbose_name='انتخاب روز های هفته'),
        ),
    ]
