# Generated by Django 4.2.1 on 2023-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_pricesetting_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='times',
            field=models.CharField(choices=[('All', 'همه زمان ها'), ('01:30', '01:30'), ('07:30', '07:30'), ('09:00', '09:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('13:30', '13:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:00', '18:00'), ('19:30', '19:30'), ('21:00', '21:00'), ('22:30', '22:30'), ('23:59', '23:59')], default='All', verbose_name='انتخاب زمان های رزرو'),
        ),
    ]
