# Generated by Django 4.2.1 on 2023-06-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_pricesetting_times'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricesetting',
            table='reserve_system_price_setting',
        ),
        migrations.AlterModelTable(
            name='reservedatetime',
            table='reserve_system_table',
        ),
    ]
