# Generated by Django 4.2.1 on 2023-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_alter_pricesetting_table_alter_reservedatetime_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedatetime',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='لطفا هزینه رزرو را به <strong>تومان</strong> وارد کنید.', max_digits=10, verbose_name='قیمت'),
        ),
    ]
